### ISSUE TITLE
with-setid-mode ignored?

### ISSUE THREAD

**Issue by darthPal** [lightsey/mod_suphp#2]
Hello, I am trying to build suphp on a Ubuntu 18.04 box with the following configure syntax:

./configure --prefix=/usr --sysconfdir=/etc/ --with-setid-mode=owner --with-logfile=/var/log/suphp/suphp.log

It builds with no errors, and config.log does have "#define OPT_USERGROUP_OWNER 1", but if suPHP_UserGroup is not specified in the apache conf i get this error:

SecurityException in Application.cpp:361: Environment variable SUPHP_USER or SUPHP_GROUP not set

It seems to me like suphp is running in paranoid mode. 

[config.log](https://github.com/lightsey/mod_suphp/files/3358194/config.log)

**Comment by lightsey** [comment]
Hmm.

The operating mode is configurable in the suphp.conf file now. The compile flag is supposed to set the default for the operating mode if it's not set to something specific in the suphp.conf file. The "--with-setid-mode=owner" should have a default behavior identical to adding ```mode=owner``` in the suphp.conf.

It's probably getting the wrong default mode setting because src/Application.cpp has no ```#include "config.h"``` line.

**Comment by darthPal** [comment]
Ah I didn't see the 'mode=owner' mentioned in the doc anywhere or I would have used that. Thank you for the reply.

**Comment by lightsey** [comment]
The default is now set correctly based on the compile time flags and the documentation has been updated to include the "mode" parameter.
